// <auto-generated />
using System;
using IcuNotes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IcuNotes.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260508105055_RecreateEverything")]
    partial class RecreateEverything
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("IcuNotes.Models.AdmissionUnitCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AdmissionUnitCatalogs");
                });

            modelBuilder.Entity("IcuNotes.Models.ArchivedPatient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CombinedHistory")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Diagnosis")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ArchivedPatients");
                });

            modelBuilder.Entity("IcuNotes.Models.ArchivedPatientDateEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArchivedPatientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArchivedPatientId");

                    b.ToTable("ArchivedPatientDateEvents");
                });

            modelBuilder.Entity("IcuNotes.Models.Cardiology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CardiacIndex")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CardiacOutput")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CentralVenousPressure")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DiastolicBloodPressure")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HeartRate")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InferiorVenaCava")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PulmonaryCapillaryWedgePressure")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SystemicVascularResistance")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SystolicBloodPressure")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("Cardiologies");
                });

            modelBuilder.Entity("IcuNotes.Models.CardiologyMedication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardiologyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Dose")
                        .HasColumnType("TEXT");

                    b.Property<int>("MedicationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CardiologyId");

                    b.HasIndex("MedicationId");

                    b.ToTable("CardiologyMedications");
                });

            modelBuilder.Entity("IcuNotes.Models.GastroIntestinal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AbdominalGirth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FeedingRoute")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("GitNotes")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasGiBleeding")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IntraAbdominalPressure")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastBowelMotionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("GastroIntestinals");
                });

            modelBuilder.Entity("IcuNotes.Models.GastroIntestinalItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("DoseOrRate")
                        .HasColumnType("TEXT");

                    b.Property<int>("GastroIntestinalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MedicationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GastroIntestinalId");

                    b.HasIndex("MedicationId");

                    b.ToTable("GastroIntestinalItems");
                });

            modelBuilder.Entity("IcuNotes.Models.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Frequency")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("IcuNotes.Models.Neurology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GcsEye")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GcsMotor")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GcsVerbal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MotorStatus")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pupils")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("Neurologies");
                });

            modelBuilder.Entity("IcuNotes.Models.NeurologyMedication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Dose")
                        .HasColumnType("TEXT");

                    b.Property<int>("MedicationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NeurologyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MedicationId");

                    b.HasIndex("NeurologyId");

                    b.ToTable("NeurologyMedications");
                });

            modelBuilder.Entity("IcuNotes.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AdmissionUnitCatalogId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bed")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Diagnosis")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdmissionUnitCatalogId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("IcuNotes.Models.PatientDateEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientDateEvents");
                });

            modelBuilder.Entity("IcuNotes.Models.PatientSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CombinedHistory")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventsTodo")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("PatientSummaries");
                });

            modelBuilder.Entity("IcuNotes.Models.ArchivedPatientDateEvent", b =>
                {
                    b.HasOne("IcuNotes.Models.ArchivedPatient", "ArchivedPatient")
                        .WithMany("ArchivedPatientDateEvents")
                        .HasForeignKey("ArchivedPatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArchivedPatient");
                });

            modelBuilder.Entity("IcuNotes.Models.Cardiology", b =>
                {
                    b.HasOne("IcuNotes.Models.Patient", "Patient")
                        .WithOne("Cardiology")
                        .HasForeignKey("IcuNotes.Models.Cardiology", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("IcuNotes.Models.CardiologyMedication", b =>
                {
                    b.HasOne("IcuNotes.Models.Cardiology", "Cardiology")
                        .WithMany("Medications")
                        .HasForeignKey("CardiologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IcuNotes.Models.Medication", "Medication")
                        .WithMany()
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cardiology");

                    b.Navigation("Medication");
                });

            modelBuilder.Entity("IcuNotes.Models.GastroIntestinal", b =>
                {
                    b.HasOne("IcuNotes.Models.Patient", "Patient")
                        .WithOne("GastroIntestinal")
                        .HasForeignKey("IcuNotes.Models.GastroIntestinal", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("IcuNotes.Models.GastroIntestinalItem", b =>
                {
                    b.HasOne("IcuNotes.Models.GastroIntestinal", "GastroIntestinal")
                        .WithMany("Items")
                        .HasForeignKey("GastroIntestinalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IcuNotes.Models.Medication", "Medication")
                        .WithMany()
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GastroIntestinal");

                    b.Navigation("Medication");
                });

            modelBuilder.Entity("IcuNotes.Models.Neurology", b =>
                {
                    b.HasOne("IcuNotes.Models.Patient", "Patient")
                        .WithOne("Neurology")
                        .HasForeignKey("IcuNotes.Models.Neurology", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("IcuNotes.Models.NeurologyMedication", b =>
                {
                    b.HasOne("IcuNotes.Models.Medication", "Medication")
                        .WithMany()
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IcuNotes.Models.Neurology", "Neurology")
                        .WithMany("Medications")
                        .HasForeignKey("NeurologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medication");

                    b.Navigation("Neurology");
                });

            modelBuilder.Entity("IcuNotes.Models.Patient", b =>
                {
                    b.HasOne("IcuNotes.Models.AdmissionUnitCatalog", "AdmissionUnitCatalog")
                        .WithMany()
                        .HasForeignKey("AdmissionUnitCatalogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AdmissionUnitCatalog");
                });

            modelBuilder.Entity("IcuNotes.Models.PatientDateEvent", b =>
                {
                    b.HasOne("IcuNotes.Models.Patient", "Patient")
                        .WithMany("PatientDateEvents")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("IcuNotes.Models.PatientSummary", b =>
                {
                    b.HasOne("IcuNotes.Models.Patient", "Patient")
                        .WithOne("PatientSummary")
                        .HasForeignKey("IcuNotes.Models.PatientSummary", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("IcuNotes.Models.ArchivedPatient", b =>
                {
                    b.Navigation("ArchivedPatientDateEvents");
                });

            modelBuilder.Entity("IcuNotes.Models.Cardiology", b =>
                {
                    b.Navigation("Medications");
                });

            modelBuilder.Entity("IcuNotes.Models.GastroIntestinal", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("IcuNotes.Models.Neurology", b =>
                {
                    b.Navigation("Medications");
                });

            modelBuilder.Entity("IcuNotes.Models.Patient", b =>
                {
                    b.Navigation("Cardiology");

                    b.Navigation("GastroIntestinal");

                    b.Navigation("Neurology");

                    b.Navigation("PatientDateEvents");

                    b.Navigation("PatientSummary");
                });
#pragma warning restore 612, 618
        }
    }
}
